Custom `User-Agent` and a more informative error message
roryrjb/iplocation pull request #35
Opened 2021-03-04 22:47 UTC by freeatnet

Hey there! Thanks for taking care of this library.

This PR includes a couple of small tweaks.
1. *Ability to set a custom `User-Agent` header.* I noticed that the provider has started returning 429 Rate Limited a bit too often. It appears that `node-fetch` is the keyword triggering this behaviour. Fair enough! Having a custom `User-Agent` fixes this issue + it's just the nice thing to do. If you have a different preference for the parameter style, let me know.
2. *Including type and value of `ip` in the `TypeError` message.* These occasionally happen to me in production, and I hope the expanded error message can provide more insight.

2021-03-04 23:16 UTC, Richienb commented
`userAgent` should be in an optional `options` object

2021-03-06 00:23 UTC, Richienb requested changes

2021-03-06 00:23 UTC, Richienb commented on source/index.ts
> +		userAgent?: string // The User-Agent header to send along. Useful if you receive unexpected 429 Rate Limited errors.
Should be as a full comment so that consumers are able to read it

2021-03-06 00:23 UTC, Richienb commented on source/index.ts
> +@param options An Options object. Optional.
I don't think it's necessary to define `options`.

2021-03-06 00:23 UTC, Richienb commented on source/index.ts
> +				"User-Agent": options.userAgent
Is setting `User-Agent` to undefined equivalent to removing the default user agent or overriding it?

2021-03-06 06:59 UTC, closed without merging

2021-03-06 06:59 UTC, freeatnet commented
I'll use my fork. Thanks for your input!