Allow a custom API key
roryrjb/iplocation pull request #38
Opened 2021-10-24 07:22 UTC by Aman1997

Fixes #36, Fixes #37

2021-10-24 07:28 UTC, Richienb requested changes
Some auto-formatting needs to be reverted

2021-10-24 07:28 UTC, Richienb commented on source/index.ts
> +	api_key: string = ""
Camel case should be used

2021-10-24 07:28 UTC, Richienb commented on source/index.ts
> +	api_key: string = ""
Should be an optional argument

2021-10-24 07:28 UTC, Richienb commented on source/index.ts
> +		`https://ipapi.co/${ip}/json/${api_key ? `?key=${api_key}` : ""}`
You can use `searchParams` instead of encoding it directly

2021-10-24 08:14 UTC, Aman1997 commented on source/index.ts
> +	api_key: string = ""
Updated

2021-10-24 08:14 UTC, Aman1997 commented on source/index.ts
> +	api_key: string = ""
Updated

2021-10-24 08:14 UTC, Aman1997 commented on source/index.ts
> +		`https://ipapi.co/${ip}/json/${api_key ? `?key=${api_key}` : ""}`
Conditionally adding the api key to the URL as searchParams.

2021-10-24 08:17 UTC, Richienb requested changes

2021-10-24 08:17 UTC, Richienb commented on source/index.ts
> +async function ipLocation(ip: string, apiKey?: string): Promise<ipLocation.ReturnType> {
This should still be in an options object

2021-10-24 08:17 UTC, Richienb commented on source/index.ts
> +			};
```suggestion
			}
```

2021-10-24 08:17 UTC, Richienb commented on source/index.ts
> +	}
By searchParams option, I mean you can pass it as the second argument to [ky](https://github.com/sindresorhus/ky)

2021-10-24 08:17 UTC, Richienb commented on source/index.ts
> +		reserved,
```suggestion
		reserved
```

2021-10-24 08:17 UTC, Richienb commented on source/index.ts
> +			code: region_code,
```suggestion
			code: region_code
```

2021-10-24 08:17 UTC, Richienb commented on source/index.ts
> +			languages: languages ? languages.split(",") : [],
```suggestion
			languages: languages ? languages.split(",") : []
```

2021-10-24 08:36 UTC, Aman1997 commented on source/index.ts
> +async function ipLocation(ip: string, apiKey?: string): Promise<ipLocation.ReturnType> {
Made apiKey parameter as part of an optional options object

2021-10-24 08:36 UTC, Aman1997 commented on source/index.ts
> +	}
Updated

2021-10-24 08:50 UTC, Richienb commented on source/index.ts
> +	const { latitude, longitude, city, reserved, region, region_code, country_name, country_code, country_code_iso3, country_capital, country_tld, country_population, country_calling_code, continent_cod
You can just reference apiKey directly and if it resolves to undefined, ky will automatically ignore it

2021-10-24 08:50 UTC, Richienb requested changes
The readme should be updated

2021-10-24 08:55 UTC, Aman1997 commented on source/index.ts
> +	const { latitude, longitude, city, reserved, region, region_code, country_name, country_code, country_code_iso3, country_capital, country_tld, country_population, country_calling_code, continent_cod
okay

2021-10-24 12:35 UTC, Richienb requested changes

2021-10-24 12:35 UTC, Richienb commented on source/index.ts
> +	const { latitude, longitude, city, reserved, region, region_code, country_name, country_code, country_code_iso3, country_capital, country_tld, country_population, country_calling_code, continent_cod
The quotes around `key` are optional.

2021-10-24 12:35 UTC, Richienb commented on README.md
> +})();
This example can be moved directly underneath the description of the `apiKey` option.

2021-10-24 12:35 UTC, Richienb commented on README.md
> +The api key for the paid version of [ipapi](https://ipapi.co/pricing/?utm_source=google&utm_term=ipapi&utm_campaign=10951547418&adgroupid=109238001284&device=c&utm_medium=cpc&utm_content=459469000491
```suggestion
An optional [ipapi](https://ipapi.co/) API key to use.
```

2021-10-24 12:35 UTC, Richienb commented on source/index.ts
> +		apiKey: string
The description and example should be added here as well in a multi-line comment.

2021-10-24 12:56 UTC, Aman1997 commented on source/index.ts
> +		apiKey: string
Added the new example within the existing commented sample code

2021-10-24 16:07 UTC, Richienb commented on source/index.ts
> +		apiKey: string
Not only should the example be in the readme, but it should also be here as well. [Example](https://github.com/sindresorhus/ky/blob/2049affe2ca939f53350fb9b7354c3ff8d2e1c1f/source/types/options.ts#L38-L73).

2021-10-24 16:07 UTC, Richienb commented on README.md
> +// using the paid tier of ipapi
These comments should be removed and the import statement should be added here.

2021-10-24 16:13 UTC, Richienb commented on README.md
> +	await ipLocation("172.217.167.78", { apiKey: 'YOUR_API_KEY'});
```suggestion
	await ipLocation("172.217.167.78", { apiKey: 'YOUR_API_KEY' });
```

2021-10-24 16:19 UTC, Aman1997 commented on source/index.ts
> +		apiKey: string
The example of how to use apiKey is added to the main index.ts file below the existing example

2021-10-24 16:25 UTC, Richienb commented on source/index.ts
> +		apiKey: string
That's not where it goes in this codebase. It should be put above the option.

2021-10-24 16:27 UTC, Aman1997 commented on source/index.ts
> +		apiKey: string
okay!

2021-10-24 16:37 UTC, Richienb commented on source/index.ts
> +		apiKey: string
Check the example again. You need to create a comment directly above `apiKey` and add the description and example of the option specifically in there which you can grab from the readme.

2021-10-24 16:59 UTC, merged

2021-10-24 17:00 UTC, Richienb commented
Thanks!

2021-10-25 03:40 UTC, vishwasnavadak commented
@Richienb Will there be a NPM release with this fix anytime soon?